### PR TITLE
Softplus activation

### PR DESCRIPTION
**Pull request by jeffin07**
Implemented SoftPlus activation mentioned in #7 
tested with test.py
plot
### files changed
acivations.py
plots.py
tests.py
tests/tests.py

### CODE REVIEW

**Comment by WuZhuoran** [comment]
You can create unit test base on @ddbourgin example:
> Thanks for these! I haven't finished going through them, but if you could include unit tests against the existing PyTorch implementations (see my hacky examples [here](https://github.com/ddbourgin/numpy-ml/blob/983e0cb226b45f586dfaaeade5a3c40d60fb7187/neural_nets/tests/tests.py#L454) for reference), that would help a ton.

You can also refer #8 pull request for further example of unit test.

**Comment by jeffin07** [comment]
@WuZhuoran  I updated the PR with unit test

**Comment by ddbourgin** [comment]
@jeffin07 - This is great! I've taken a quick glance, and this looks basically perfect. I'll go over in a bit more detail tonight, but should be able to merge shortly.

**Comment by ddbourgin** [comment]
Beautiful. Fixed small bugs in the unit tests and now we're ready to go. Merging!

**Pull request merged**
