### PR TITLE
Softsign activation function 

### PR DESCRIPTION
**Pull request by jeffin07**
Implemented Softsign activation and unit test for sotfsign
plot

files changed
- activations.py
- test.py
-../tests/tests.py

### CODE REVIEW

**Comment by ddbourgin** [comment]
Thanks, @jeffin07! I'm less inclined to keep adding activation functions, since I think we've already covered the majority of nonlinearities used in modern deep learning. If there's a compelling reason to add soft-sign (e.g., a paper / architecture that reports good results using soft-sign), let me know, but otherwise I think we're probably fine keeping things as they are.

**Comment by jeffin07** [comment]
@ddbourgin i didn't see you closed #7 :) . I was thinking of doing a loss function  do you have any suggestions ?

**Comment by ddbourgin** [comment]
That sounds great! Perhaps a cosine or KL-divergence loss? Depending on your enthusiasm, more sophisticated things like triplet loss or connectionist temporal classification loss would be awesome, though there's a reason why I've put them off ;-)

**Comment by jeffin07** [comment]
@ddbourgin thats great will close this PR now  :)

**Pull request closed without merging**
